version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

volumes:
  redis_data:
  mysql_data:
